[tool.poetry]
name = "baca2-broker"
version = "0.1.0"
description = ""
authors = ["Bartosz Deptuła <barti.deptula@gmail.com>"]
readme = "README.md"
packages = [{include = "broker"}]

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.1"
baca2-package-manager = "0.2.13"
requests = "^2.31.0"
coverage = "^7.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
